### ISSUE TITLE
Unable to write channel atrribute -22

### ISSUE THREAD

**Issue by Paco93** [Manawyrm/sdrsharp-plutosdr#1]
Thanks for the effort in producing a plugin for SDR#
Starting the receiver provide me with the error in the title.
Any ideas?

I am using the latest version of SDR# (x86) sand copied the libiio dlls in the SDR# directory

**Comment by Manawyrm** [comment]
Hi,

yes. There's some confusion about the sample rates, that causes this error. 
I don't know yet why this happens, but it only does happen at 1 MSPS. 
On my machine at home, 1 MSPS works. But on 2 other test PCs I tried, 1 MSPS gives the -22/invalid argument error. 

Please update the dll from https://tbspace.de/content/downloads/sdrsharp-plutosdr/SDRSharp.PlutoSDR.dll 

I have added a new sample rate of 2.1 MSPS, that seems to work nicely. 
2.5 MSPS also seems to work, but my PC can't handle it. Maybe yours is fast enough. 

I will polish the lib quite a bit more and implement some better error handling. That way, errors like these shouldn't be shown to the user anymore.

**Comment by Manawyrm** [comment]
I would also suggest that you reconfigure the env-variables of your PlutoSDR to the AD9364 configuration: 
https://wiki.analog.com/university/tools/pluto/users/customizing#updating_to_the_ad9364

This gives you much wider tuning range and is currently the only tested version of the SDR.

**Comment by Paco93** [comment]
Thanks.
Actually I have three sample rates to choose from: 1Msps, 2 Msps and 2.5 Msps.
Apparently the first two gives the error whilst the last works very well!
I will try the new updated dll.
Regards
Paco

**Comment by Manawyrm** [comment]
The new .dll adds the new 2.1MSPS mode, but if 2.5MSPS works stable for you, thats wonderful. 

Also, I did a bit more error handling, but it's still a long way from done.
