### ISSUE TITLE
"Slow attack AGC"  issue after update to V0.27

### ISSUE THREAD

**Issue by F6DZP** [Manawyrm/sdrsharp-plutosdr#10]
All was running well with SDRsharp and my Pluto . but was obliged to use 3MS rate (4MS gave me glitches, impossible to use it). FM broadcast was received very well and with a good sound

I have update to v0.27 firmware:
=> now there is an issue if we use the "Slow attack AGC" ==> we get a message "unable to write channel attribute -95"
If I do not select this option, all seems to run well.

I will go back to firmware 0.26 and I have no more the "Slow attack AGC" issue.

thank you for this good work.

**Comment by Manawyrm** [comment]
Hi, 

thanks for the report! I haven't yet had a chance to update and test my PlutoSDR, so I'll make sure to do just that. I hope I can find time for that during the upcoming easter holidays.

**Comment by Manawyrm** [comment]
Hi,

I just released a new version: 
https://github.com/Manawyrm/sdrsharp-plutosdr/releases/tag/v0.4.2

Please update your firmware to 0.27 again and let me know if it works better (it does for me). 
There's also rudimentary support for direct connection via USB (instead of TCP). 
I'll implement USB auto detection on another day.

**Comment by innovak** [comment]
Nope,if slow_attach AGC option was selected, press start button still report "Unable to write channel attribute -95".

**Comment by Manawyrm** [comment]
Oops, sorry!
Please try this release: 
https://github.com/Manawyrm/sdrsharp-plutosdr/releases/tag/v0.4.3

It now works properly.

**Comment by innovak** [comment]
It works fine now,Thank you!

**Comment by Manawyrm** [comment]
Wonderful :)
