### ISSUE TITLE
PlutoSDR does not tune to selected stored frequency.

### ISSUE THREAD

**Issue by beta-tester** [Manawyrm/sdrsharp-plutosdr#11]
when i double-click to a stored frequency of the "Frequency Manager" the PlutoSDR does not tune to the selected frequency, does not set the bandwidth and does not change the mode of demodulation.

it is not an issue when i use RTL-SDR (USB).

i used
sdr-sharp rev 1666,
your sdrsharp-plutosdr plugin version 0.4.3 beta (shown as 0.4.2 on the plugin dialog itself),
PlutoSDR has 70-6000MHz hack is applied and the firmware version is v0.28.

![issue sdr-sharp plutosdr frequency manager](https://user-images.githubusercontent.com/4750719/40483940-28a38f1a-5f5a-11e8-900f-d0ef4b578bfb.PNG)

**Comment by Manawyrm** [comment]
Yes, this is very unfortunate. 
This is not a technical problem, but a political limitation in SDR#.
Other plugins (like demodulators for 3rd party protocols like Meteor-M2 or external RDS decoders) also don't work.

You'll need to buy an AirSpy for these to work properly. I'm sorry, but there's nothing I can do.
