### ISSUE TITLE
SDR# Plugin's Don't Work

### ISSUE THREAD

**Issue by AlexLao512** [Manawyrm/sdrsharp-plutosdr#16]
It seems like Zoom FFT and Audio Noise Reduction plugin's among others do not work with the PlutoSDR but work with an RTL-SDR.

**Comment by Manawyrm** [comment]
Yes, that‘s correct. Unfortunately that‘s not a bug, but a political decision by the SDR# authors. Nothing I can do about it. 
Plugins can only be used by the integrated FrontEnds, not by third-party frontends. 

I can recommend buying an AirSpy, though. It‘s good hardware and you‘ll get the full software. 

—
Tobias Mädel
t.maedel@alfeld.de
PGP: 3A69 E9AF 3FA9 3BCF FE50 9694 494E 2F56 C304 60E1
https://tbspace.de

Am 05.09.2018 um 19:58 schrieb Alex Lao <notifications@github.com>:

It seems like Zoom FFT and Audio Noise Reduction plugin's among others do not work with the PlutoSDR but work with an RTL-SDR.
