### ISSUE TITLE
The type or namespace name `IIQStreamController' could not be found

### ISSUE THREAD

**Issue by soundart** [Manawyrm/sdrsharp-plutosdr#21]
Hi,

I cannot build the plugin. What I did:

Build sdrsharp from here  https://github.com/cgommel/sdrsharp

xbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Release

then cloned sdrsharp-plutosdr, linked the two dlls Radio, Common and started buiilding

xbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Release

Result
`
Build FAILED.

Warnings:

/projects/pluto/sdrsharp-plutosdr/SDRSharp.PlutoSDR.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.

Errors:

/projects/pluto/sdrsharp-plutosdr/SDRSharp.PlutoSDR.sln (default targets) ->
(Build target) ->
/projects/pluto/sdrsharp-plutosdr/PlutoSDR/SDRSharp.PlutoSDR.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	PlutoSDRIO.cs(10,52): error CS0246: The type or namespace name `IIQStreamController' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(10,86): error CS0246: The type or namespace name `ISampleRateChangeSource' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(10,111): error CS0246: The type or namespace name `IFloatingConfigDialogProvider' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(10,142): error CS0246: The type or namespace name `ITunableSource' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(10,158): error CS0246: The type or namespace name `IControlAwareObject' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(10,179): error CS0246: The type or namespace name `ISpectrumProvider' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(183,14): error CS0246: The type or namespace name `ITunableSource' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(191,14): error CS0246: The type or namespace name `ITunableSource' could not be found. Are you missing an assembly reference?
	PlutoSDRIO.cs(198,14): error CS0246: The type or namespace name `ITunableSource' could not be found. Are you missing an assembly reference?

	 1 Warning(s)
	 9 Error(s)

`

I cannot find IIQStreamController in sdrsharp. I think I am missing something....

**Comment by Manawyrm** [comment]
Hi!

SDR# has unfortunatly gone closed source a long while ago.
The old source code is still online, but it's far from the current version.

My plugin is for the propritary closed source version and can only be compiled against those binaries, sorry! 

Best regards,
Tobi

**Comment by soundart** [comment]
Hi,

ah ok I did not see that. 

I think I would see more errors if libiio bindings would not work. I did 
`sudo apt install libiio-cil-dev`

**Comment by Manawyrm** [comment]
Very interesting! 
But still: 
https://github.com/Manawyrm/sdrsharp-plutosdr/blob/master/PlutoSDR/NativeMethods.cs
does native .dll syscalls. Those will not work, even with the correct bindings. 
Especially the reflection trick into the libiio-cil binding will do strange things on non-windows platforms. 
It directly fetches the reference to the native libiio device handle. Not sure how compatible that is to linux code. You might be able to just change that to libad9361.so and go from there...
