### ISSUE TITLE
Unable to create buffer

### ISSUE THREAD

**Issue by Hysteria1212** [Manawyrm/sdrsharp-plutosdr#22]
Hi,

if I hit the play button in sdr# I only get the message "unable to create buffer" .  I'm able to connect to the device in the settings of your plugin and I've changed the sampling rate too.

I'm using the latest sdr#, latest pluto firmware and the latest of your plugin.

BTW I've flashed the plutoweb image on it.

Cheers
Norbert

**Comment by Hysteria1212** [comment]
I did a flash with the original firmware by Analog. Now it works,

**Comment by Manawyrm** [comment]
Hi, yes, the PlutoWeb firmware unfortunately doesn't contain the neccesary server.
