### ISSUE TITLE
frequency tuning via gpredict plugin does not work

### ISSUE THREAD

**Issue by dc6jn** [Manawyrm/sdrsharp-plutosdr#24]
Hi,
I use adalm-pluto as receiver. Works fine so far. I tried to use gpredict to adjust the receive frequency according to the doppler shift of the current satellite. While the gpredict-plugin shows the correct frequency, nothing changes. If I switch to a rtl-sdr stick everything works, so I guess this is related to the pluto driver.
 Regards

**Comment by Manawyrm** [comment]
Hallo Jürgen,

leider ist das ein politisches Limit innerhalb von SDR#.
Es wird Drittanbieter Frontend-Plugins nicht erlaubt, bestimmte Funktionen (wie z.B. externe Plugins oder die SNR-Anzeige) zu nutzen.

Die Firma hinter SDR# möchte hiermit erreichen, dass man ihre AirSpy Produkte kauft.

Da kann ich also leider nichts gegen machen.

Viele Grüße,
Tobias
DL4TMA

**Comment by dc6jn** [comment]
Hallo Tobias,
danke für die schnelle Antwort. Ich habe mich nur gewundert das es mit den einfachen rtl sticks funktioniert. Aber möglicherweise ist das ja ein interner Treiber.
Vielen Dank trotzdem für die Treiberprogrammierung.
Grüße 
 Jürgen
 dc6jn

Am 25. September 2019 16:26:12 MESZ schrieb "Tobias Mädel" <notifications@github.com>:
>Hallo Jürgen,>
>>
>leider ist das ein politisches Limit innerhalb von SDR#.>
>Es wird Drittanbieter Frontend-Plugins nicht erlaubt, bestimmte
>Funktionen (wie z.B. externe Plugins oder die SNR-Anzeige) zu nutzen.>
>>
>Die Firma hinter SDR# möchte hiermit erreichen, dass man ihre AirSpy
>Produkte kauft.>
>>
>Da kann ich also leider nichts gegen machen.>
>>
>Viele Grüße,>
>Tobias>
>DL4TMA>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Manawyrm/sdrsharp-plutosdr/issues/24#issuecomment-535049034

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Manawyrm** [comment]
Jo, RTL-SDR ist ein interner Treiber. 
In SDR# gibt es da eine Whitelist, wo der RTL-SDR Treiber explizit erlaubt wird.

Viele Grüße,
Tobias
