### ISSUE TITLE
installation troubles

### ISSUE THREAD

**Issue by JSEsq** [Manawyrm/sdrsharp-plutosdr#25]
Hello,

i use the sdr# v.1.0.0.1777 (tried both official and community editions) on windows 10 x64 and i have trouble using plutosdr plugin (windows binaries).
First of all, the frontends.xml is missing. Should I create it manually?
I tried to insert xml entry into plugins.xml, but plutosdr doesn't appears in sources list.

**Comment by Manawyrm** [comment]
Hi, 

doesn't look too good unfortunately. 
I haven't looked into the issue too deeply, but SDR# seems to have a new FrontEnd API, which is incompatible with this plugin. 

I'd suggest you use the last SDR# release before this change or the "-noskin" variant which is linked on the download page of SDR#. It still has the Frontends.xml and should work fine.

SDR# developers have previously mentioned how they don't really like 3rd-parts frontends, so I'm not sure if I should invest any more development time into updating the API. (especially as I couldn't find any info on the specific changes right away).
