### ISSUE TITLE
Will this work via direct Ethernet connection like into the Pluto+ ?

### ISSUE THREAD

**Issue by waterwin** [Manawyrm/sdrsharp-plutosdr#26]
Can I set the IP address of the network connected Pluto+ ?
Or is this only working via a usb connected (local) Adalm Pluto or Pluto+ ?

Thanks for any suggestions to solve.

de Erwin
PE3ES / F4VTQ

**Comment by Manawyrm** [comment]
Yes, in fact: It only supports network.

**Comment by waterwin** [comment]
Yes I have found the settings page (sorry) Then it works for me with a local connected ethernet (via usb) with the standard ip address as my wifi connection into the other one is too slow to handle the data rate.
At the moment switching between two radios needs totally closing down SDR# as else you can not change the Device-URI field. Probably because there is currently no way to do a disconnect?

**Comment by Manawyrm** [comment]
I'm not 100% sure, you might be able to change the Device-URI field after Stopping SDR#? 
But yeah, closing it down is the "proper" way for now.

**Comment by waterwin** [comment]
Thank you for your very fast responses.
