### ISSUE TITLE
SDR# does not detect plugin

### ISSUE THREAD

**Issue by mgua** [Manawyrm/sdrsharp-plutosdr#27]
Apparently SDR# developers changed how they reference plugin relatively to the main SDR# folder.
File FrontEnds.xml is not there anymore, and its presence appears irrelevant. 
SDRSharp.config file has an explicit entry key="core.pluginsDirectory"
There is a Plugins.xml file with a test entry. 

If I place sdrsharp-plutosdr files in the "Plugins" subfolder and edit the plugins.xml file adding the line
  add key="PlutoSDR" value="SDRSharp.PlutoSDR.PlutoSDRIO,SDRSharp.PlutoSDR"
when i run SDR# a "PluginError.log" is created with the following content.

---------
*** Plugin Load Error - 2022-01-02 11:45:46.754
Config Key   'PlutoSDR'
Type         'SDRSharp.PlutoSDR.PlutoSDRIO, SDRSharp.PlutoSDR, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null'
Message      'Specified cast is not valid.'
Stack Trace
   at SDRSharp.MainForm.InitializeSharpPlugins()
----------

Any Suggestions?
Marco Guardigli

**Comment by Manawyrm** [comment]
Hello Marco,

yes, unfortunately as mentioned in the README, external Frontends are no longer supported by SDR# for political reasons.
The developers want you to buy an AirSpy radio instead.

Not much I can do about that, sorry. 
Use the latest release before that change (link is in the readme) or buy another radio.

**Comment by mgua** [comment]
Tobias,

Thank you for your quick reply and explanation.
I found this site with old sdr# versions. 
https://www.iz3mez.it/software/SDRSharp/  
I downloaded version 1583 (as seen on picture in the tutorial) and it 
works.

73,
Marco






From:   Tobias Mädel ***@***.***>
To:     Manawyrm/sdrsharp-plutosdr ***@***.***>
Cc:     mgua ***@***.***>, Author ***@***.***>
Date:   02/01/2022 14:45
Subject:        Re: [Manawyrm/sdrsharp-plutosdr] SDR# does not detect 
plugin (Issue #27)



Hello Marco,
yes, unfortunately as mentioned in the README, external Frontends are no 
longer supported by SDR# for political reasons.
The developers want you to buy an AirSpy radio instead.
Not much I can do about that, sorry.
Use the latest release before that change (link is in the readme) or buy 
another radio.
73,
Tobias
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>
