### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by drbam** [Manawyrm/sdrsharp-plutosdr#5]
![connection failed](https://user-images.githubusercontent.com/2669743/29559882-fda5a89c-8738-11e7-9dc8-e21a0f1978c8.PNG)
Please your help !

Borislav,
LZ1CUB

**Comment by Manawyrm** [comment]
Hi, 

can you use a webbrowser to open http://192.168.2.1 ? 
If not: you might have a problem with missing drivers. 

If this works, try downloading this program: https://github.com/analogdevicesinc/iio-oscilloscope/releases
and connecting to the device via "remote network" 192,168.2.1.

**Comment by drbam** [comment]
Problem was in conflict with default IP in WiFi router, covered both 192.168.1.1 and (hide) 192.168.2.1.
Cleared simple by "Run as administrator" of SDRSharp.exe !

Regards,
Borislav
LZ1CUB
