### ISSUE TITLE
Frequency range extension

### ISSUE THREAD

**Issue by iroks** [Manawyrm/sdrsharp-plutosdr#6]
Hello,
I got my Pluto several days ago and tried to extend the frequency range as described on the site https://wiki.analog.com/university/tools/pluto/users/customizing in the Updating to the AD9364 section. 
The error message „Unsupported LO frequency“ is prompted If I tune to the lower or higher frequency. All further frequency changes (also in official Pluto range) do not work before SDR# will not be restarted.
Do you have an idea what can be wrong?
 
![grafik](https://user-images.githubusercontent.com/13328524/29811186-e9feb198-8ca2-11e7-8286-f000951fed9e.png)
![grafik](https://user-images.githubusercontent.com/13328524/29811198-ee6839b6-8ca2-11e7-9de2-ebe45c0f638f.png)

**Comment by Manawyrm** [comment]
Hi,

yes. Unfortunatly there is an error in the Analog Devices wiki.
The `` and ´´ characters in the wiki are wrong. 

it should be standard "-characters. 
Try the commands again with "ad9364", and it should work :)

**Comment by iroks** [comment]
many thanks for the fast reply. It works now. 
![fmworks](https://user-images.githubusercontent.com/13328524/29811680-a1ac61cc-8ca4-11e7-9362-2d03ae0d6bd6.jpg)

**Comment by Manawyrm** [comment]
Wonderful! Remember to turn the gain up ;)
