### ISSUE TITLE
frequency control using SDR# plugin

### ISSUE THREAD

**Issue by mlhammond** [Manawyrm/sdrsharp-plutosdr#8]
There is a plugin for SDR# that connects via DDE to a satellite tracking program like SatPC32 or WXtrack so the frequency information of the tracking program is sent to SDR# and then the frequency is changed in the SDR device via SDR#.   Currently the frequency of PlutoSDR does not change as expected. Is there perhaps a simple change that you might make in the PlutoSDR to allow the frequency to change via the plugin?  The SDR# plugin, current is V8, including the source code used is here: http://www.satsignal.eu/software/DDETracker.html

**Comment by Manawyrm** [comment]
Hi,

I'm very sorry, but this is a limitation in SDR#, which doesn't allow third-party FrontEnds to use frequency tracking plugins, or any plugin that uses I/Q data. 
You need to buy an AirSpy for that.

**Comment by mlhammond** [comment]
Thank you Tobias for a great plugin. Nice work!  I am sad to learn that frequency control won't work with PlutoSDR.  But it is still very useful for amateur radio thanks to you.   I have an Airspy and Airspy+.  Also I have a Funcube dongle pro and pro plus both of which actually do allow the Doppler frequency control as well.  Different designs I am sure.  Again thanks!  If there is a version you would like tested sometime please let me know. 

Best, 

Mark L. Hammond
